FinanceApp/Models/ErrorViewModel.cs
namespace FinanceApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinanceApp/Models/Expense.cs
using System.ComponentModel.DataAnnotations;

namespace FinanceApp.Models
{
    public class Expense  
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Description { get; set; } = string.Empty;
        [Required]
        [Range(0.01,double.MaxValue, ErrorMessage ="amount needs to be verefied")]
        public double Amount { get; set; }
        [Required]
        public string Category { get; set; }= string.Empty;
        public DateTime Date { get; set; }= DateTime.Now;

    }
}

FinanceApp/Controllers/ExpensesController.cs
using FinanceApp.data;
using FinanceApp.data.Services;
using FinanceApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinanceApp.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly IExpensesService _service;

        public ExpensesController(IExpensesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var expenses = await _service.GetAll();
            return View(expenses);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Expense expense)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _service.Add(expense);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    // Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(expense);
        }
        public IActionResult GetChart()
        {
            var data = _service.GetChartData();
            return Json(data);
        }
    }
}

FinanceApp/Views/Expenses/Create.cshtml
@model FinanceApp.Models.Expense


<h2>
    Add Expense
</h2>

<form asp-action="Create" method="post">
    <div>
        <label asp-for="Description" class="form-label"> </label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div>
        <label asp-for="Amount" class="form-label"> </label>
        <input asp-for="Amount" class="form-control" />
    </div>
    <div>
        <label asp-for="Category" class="form-label"> </label>
        <input asp-for="Category" class="form-control" />
    </div>
    <div>
        <label asp-for="Date" class="form-label"> </label>
        <input asp-for="Date" class="form-control" />
    </div>-
    <button type="submit" class="btn btn-primary" style="margin-top:10px;"> Add Expense</button>
</form>

FinanceApp/Views/Expenses/Index.cshtml
@model IEnumerable<FinanceApp.Models.Expense>

<h2> Expenses </h2>
<a asp-controller="Expenses" asp-action="Create" class="btn btn-primary" style="margin-bottom: 20px;">New Expense</a>

<div class="container">
    <table class="table table-bordered">
        <thead class="table-light">
            <tr>
                <th>
                    Description
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Category
                </th>
                <th>
                    Date
                </th>


            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td> @item.Description</td>
                    <td> @item.Amount $</td>
                    <td> @item.Category</td>
                    <td> @item.Date.ToString("yyyy-MM-dd")</td>
                </tr>
            }

        </tbody>
    </table>

</div>

<h2> Expenses Overview</h2>
<div>
    <canvas style="max-width: 450px; max-height:450px;" id="myChart"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const ctx = document.getElementById('myChart');

    fetch('/Expenses/GetChart')
        .then(response => response.json())
        .then(data => {
            new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: data.map(d => d.category),
                    datasets: [{

                        data: data.map(d => d.total),
                    }]
                },

            });

        })


</script>

FinanceApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

FinanceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanceApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinanceApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinanceApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FinanceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>